import 'server-only'

import type { DatasetProfile } from '@/lib/ai/dataset-profile'
import type { TriplestoreProvider } from '@/lib/runtime/contracts'

const DIALECT_NOTES: Record<TriplestoreProvider, string> = {
  qlever:
    'Engine: QLever. Full SPARQL 1.1 SELECT support and fast aggregation. SPARQL Update is NOT supported (this tool is read-only anyway). Full-text search uses ql:contains-word / ql:contains-entity, but prefer the search_entities tool instead.',
  virtuoso:
    'Engine: Virtuoso. SPARQL 1.1 with Virtuoso extensions. Full-text search is available via `?o bif:contains "term"`, but prefer the search_entities tool instead.',
  oxigraph:
    'Engine: Oxigraph. Strict SPARQL 1.1. No full-text search support; resolve entities with the search_entities tool, or fall back to FILTER with STRSTARTS/CONTAINS on label properties.'
}

export interface PromptContext {
  profile: DatasetProfile | null
  /** Rendered profile text ready for the model, or null when unavailable. */
  profileText: string | null
  provider: TriplestoreProvider
}

export function buildSystemPrompt(context: PromptContext): string {
  const { profile, profileText, provider } = context
  const prefixes = profile?.prefixes ?? {}
  const prefixBlock = Object.entries(prefixes)
    .map(([prefix, namespace]) => `PREFIX ${prefix}: <${namespace}>`)
    .join('\n')

  const parts: string[] = []
  parts.push(
    'You answer questions about the RDF dataset behind a SPARQL endpoint by writing and running SPARQL queries. You are working inside RDF Workbench, a tool for exploring triplestores.'
  )
  parts.push('')
  parts.push('Hard rules:')
  parts.push(
    '- NEVER invent an IRI, class, or predicate. Every class and predicate you use must come from the dataset profile below, or from entities returned by the search_entities tool.'
  )
  parts.push(
    '- Resolve any named entity from the question (people, places, concepts) to a concrete IRI with search_entities BEFORE writing a query that references it.'
  )
  parts.push(
    '- Only use the run_readonly_query tool. It accepts SELECT and ASK queries only, rejects SERVICE, and caps LIMIT automatically.'
  )
  parts.push(
    '- If a query fails validation or returns zero rows, revise it: follow the predicate and class hints in the tool output, try alternative properties from the profile, relax filters, or search again with a different term. At most two or three revisions, then explain what you could not find.'
  )
  parts.push('- Use the declared PREFIXes in every query.')
  parts.push(
    '- Add a sensible LIMIT (100 or less) to exploratory queries. The tool enforces a hard cap anyway.'
  )
  parts.push(
    '- Match literal filters to the sample value formats shown in the profile (dates, language tags, datatypes).'
  )
  parts.push(
    '- End your final answer with the verified SPARQL query in a ```sparql fenced block so the user can inspect, run, and save it.'
  )
  parts.push('')
  parts.push(DIALECT_NOTES[provider])
  if (prefixBlock) {
    parts.push('')
    parts.push('Declared prefixes:')
    parts.push(prefixBlock)
  }

  if (profileText) {
    parts.push('')
    parts.push(
      'The dataset profile below was generated by introspecting the endpoint. It lists classes with instance counts, properties per class with usage counts, the classes or datatypes property values have, and sample values. Treat it as the source of truth for the dataset vocabulary.'
    )
    parts.push('---')
    parts.push(profileText)
  } else {
    parts.push('')
    parts.push(
      'No dataset profile is available. Discover the vocabulary cautiously: start from entities found with search_entities and inspect which predicates they use before writing the final query.'
    )
  }

  return parts.join('\n')
}
